name: Bug Report
description: File a bug report to help improve AIMA
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill in the sections below.

  - type: input
    id: version
    attributes:
      label: AIMA Version
      description: What version of AIMA are you running?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      options:
        - Platform / API
        - Module 1 - Customer Intelligence
        - Module 2 - Campaign Predictor
        - Module 3 - Content Studio
        - Module 4 - Brand Monitor
        - Module 5 - Attribution Engine
        - Module 6 - CLV and Churn
        - Module 7 - AI Agent
        - Data Connectors
        - Frontend
        - Infrastructure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Start the API with docker-compose up
        2. Call POST /api/v1/modules/customer-intelligence/segment
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      render: shell
