name: Feature Request
description: Suggest an idea or improvement for AIMA
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: module
    attributes:
      label: Module this relates to
      options:
        - New Module
        - Module 1 - Customer Intelligence
        - Module 2 - Campaign Predictor
        - Module 3 - Content Studio
        - Module 4 - Brand Monitor
        - Module 5 - Attribution Engine
        - Module 6 - CLV and Churn
        - Module 7 - AI Agent
        - Data Connectors
        - Frontend
        - Infrastructure
        - Research / Papers
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: A clear description of the marketing or technical problem.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should AIMA solve this?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered.
